### ISSUE TITLE
basic land generation

### ISSUE THREAD

**Issue by discomethod** [copperdogma/mtgen#1]
i've been using the booster simulator to select 36 boosters to emulate opening a booster box, but i've noticed that the basic lands generated are always only forests/plains. the odds of that happening just by chance (assuming uniform distribution between the 5 basic land types) are astronomically small.

**Comment by copperdogma** [comment]
Which set are you simulating?

**Comment by discomethod** [comment]
just tried again with 36 packs each of OGW and BFZ, only forests and plains

**Comment by copperdogma** [comment]
Right you are! I recently upgraded the generator and it messed up on the lands because of the identical card numbers on the full- vs. normal-art basic lands cards.

All fixed now. Thanks for the heads up!
