### ISSUE TITLE
License

### ISSUE THREAD

**Issue by liebig** [copperdogma/mtgen#15]
First of all I want to say thank you for this awesome project. Please don't stop expanding it. But I wondered on which license this library is provided? Thank you.

**Comment by copperdogma** [comment]
Glad you like!

I hadn't thought about it. I have now that you've asked and licensed it under an MIT-style license. See my main README: https://github.com/copperdogma/mtgen/blob/master/README.md

I would love to know what you'd want to use any part of it for.
