### ISSUE TITLE
Mismatching set codes

### ISSUE THREAD

**Issue by goblin** [copperdogma/mtgen#17]
Hello,

I've also noticed in your tree that some sets have different 3-letter codes than the official / mtgjson ones, namely:

* `M25` should be `A25`
* `NMS` should be `NEM`
* `UN3` should be `UST`

That's not a big deal, I can cope with it easily, but I just thought maybe you want to have them the same as the official ones (they probably changed at some point).

**Comment by copperdogma** [comment]
I think mtgjson may be mistaken.

The closest to "official" I can find is wotc's Masters 25 page which shows the twitter tag as mtgm25: https://magic.wizards.com/en/products/masters-25

NEM - yup you're right.. I think I got mine way back off an outdated version of MTG Wiki

UN3 - Again.. Not sure. I can't find an official source and wotc's product page has the twitter code as mtgun3: https://magic.wizards.com/en/products/unstable

**Comment by goblin** [comment]
Hmm OK, I admit I just checked on Wikipedia but now I'm not sure where they got their sources from. Feel free to close this if you're sure yours are better ;-)

**Comment by copperdogma** [comment]
Aaaaannd you're right again;)

Renamed via this PR: https://github.com/copperdogma/mtgen/pull/37

**Comment by goblin** [comment]
Thanks, but I don't think this worked. PR #37 seems to be merging master into the modularity branch, and in master (and modularity for that matter) set codes are still as they were.

**Comment by copperdogma** [comment]
Ha! Man I'm bad at this. I somehow fixed it, made a commit but failed to actually merge it, pushed it to prod, and then lost all the changes. But prod was updated.

Anyway, I rebuilt it and ACTUALLY made a proper commit to master this time: https://github.com/copperdogma/mtgen/commit/6562ed0dfc3bd25bb0c87258e9020f3925338255

Thanks!

**Comment by goblin** [comment]
:+1:
