### ISSUE TITLE
Feature Request: API to generate packs

### ISSUE THREAD

**Issue by Meerkov** [copperdogma/mtgen#22]
Generating packs correctly requires a lot of special knowledge, and most projects do it wrong (e.g. pack is missing a color, or WAR doesn't do the Planeswalker requirements correctly, etc).

It would be nice if there was an API to generate a booster so other projects could make use of all the work this project put into generating the packs.

**Comment by goblin** [comment]
@Meerkov ah yes, exactly what I was talking about 5 years ago, and finally got around to doing, if you're still interested: https://github.com/copperdogma/mtgen/pull/34 . Waiting to see what @copperdogma says, hope this gets merged. If it is, this could be a stub for a future more polished API.

**Comment by copperdogma** [comment]
Hey @Meerkov. Not sure if you still care 3 years later, but... resolved! You can now run it locally. Also I rewrote it in nodejs so it's more portable across systems if you want to run the web version locally.
