### ISSUE TITLE
Kaldheim Basic Land slot generating Faceless Haven and Shimmerdrift Vale

### ISSUE THREAD

**Issue by d-forman** [copperdogma/mtgen#25]
The Kaldheim packs are generating the above lands (Faceless Haven and Shimmerdrift Vale) in the basic land slot.  These two lands shouldn't be available in the basic land slot for draft boosters.  They should be generating in rare slot for Faceless Haven or in the common slot for Shimmerdrift Vale.
P.S. Thanks for providing a cool site!

**Comment by copperdogma** [comment]
Right you are. All fixed up! Thanks for letting me know.
