### ISSUE TITLE
Double-Faced Cards won't Import in Arena

### ISSUE THREAD

**Issue by jbaumadsen** [copperdogma/mtgen#26]
It would be nice if you could import exported sets into an Arena deck. A set I tried to import contained some DFCs by the reverse side name and some by the names of both sides. Arena threw errors for DFCs referenced by anything other than just the front side.

-Johnny
P.S.  This generator is awesome!

**Comment by copperdogma** [comment]
Easy enough! I'm already supporting half a dozen export formats. It's easy to add more.

Do you know if the Arena format has a standard? Do you have one that imports properly you could attach? I don't use Arena.

**Comment by copperdogma** [comment]
Okay I started playing Arena and then remembered this bug;) The ability to export to MtG: Arena format has been added.
