### ISSUE TITLE
NEO: No double-faced C/U in draft boosters

### ISSUE THREAD

**Issue by mikeMC87** [copperdogma/mtgen#27]
There [should be 1 C/U double-faced card in each NEO draft booster](https://magic.wizards.com/en/articles/archive/feature/kamigawa-neon-dynasty-product-overview-2022-01-27), but this is not the case on mtggen

**Comment by copperdogma** [comment]
Right you are. All fixed.

**Comment by mikeMC87** [comment]
quick work! thanks!
