### ISSUE TITLE
Return to Ravnica guild packs mislabeled

### ISSUE THREAD

**Issue by gnostechnician** [copperdogma/mtgen#3]
The packs are labelled incorrectly. They always give the correct guild's promo and gate, but the rest of the pack consists of another guild. Azorius is correct, but Golgari contains Izzet, Izzet contains Rakdos, Rakdos contains Selesnya, and Selesnya contains Golgari. (The Gatecrash promo packs are fine as far as I can see.)

**Comment by copperdogma** [comment]
Sorry to take so long.. I actually used the pack layouts someone compiled
online. I know they're a little odd, what with including other guild's
cards in the main guild's packs, but apparently that's how they ended up.

This is the source I used:
http://www.mtgsalvation.com/forums/magic-fundamentals/magic-software/337223-rtr-and-gtc-guild-pack-contents

Do you have a better source? If so I'll update the pack contents.
