### ISSUE TITLE
Issue With Arabian Nights Rare Generation

### ISSUE THREAD

**Issue by Khaldei** [copperdogma/mtgen#4]
When generating boosters for Arabian Nights, there are some cards that will never generate in the boosters.  For example, generate 1200+ boosters of Arabian Nights, then sort by "Name".  You'll see that there are 0 'Aladdin', 0 'Aladdin's Lamp', 0 'Aladdin's Ring', 0 'Ali From Cairo', etc.  In fact, you can generate as many boosters as you want, and ultimately, you will only generate 45 unique cards in various counts (you can test this through the "Export" tool that gives you unique card count).

**Comment by copperdogma** [comment]
Fixed!

I got the card data from wotc's site, and although they only printed two rarities of card for Arabian Nights (common and uncommon), they included two other rarities in their card data (b = basic land for the single mountain in the set, and r = rare = actually a printing error; they were uncommon). So the booster now includes 6 common/mountain and 2 uncommon/rares.

So the cards are all in there now.
