### ISSUE TITLE
Unhinged's "Who/What/When/Where/Why" card has too high chance

### ISSUE THREAD

**Issue by goblin** [copperdogma/mtgen#6]
Because the Who/What/When/Where/Why card from Unhinged is listed 5 times (once for each sub-card), it has 5x higher chance of being generated than a normal Rare card. I've tested this and indeed it seems it's rolled about 5x as often as, say Rare-B-Gone, another rare card from this set.

I stumbled upon this during my examination of how split cards work ;-)

EDIT/APPEND: note that the name of this generated card will appear either as Who, What, When, Where or Why. But they're all the same physical card, really.

**Comment by copperdogma** [comment]
Fixed!

I sourced the data from mtgjson.com and they split the card into five individual cards. I've collapsed them back into one.

**Comment by goblin** [comment]
Thanks!

It's quite educational to see what you've changed to fix it :-) I didn't know you could add exceptions this way.

I'm a little concerned about other split cards though - they may have 2x higher chance so probably not very noticeable, but it may be worth adding support for them. Data from mtgjson contains `"layout":"split"` which _could_ be used to automatically handle such cards. Would have to automatically rename them to something like `join(' / ', names)` and delete the other instances. But it's probably quite complicated and may not be worth it.

Thanks again for fixing this one :-)

**Comment by copperdogma** [comment]
Yeah I keep upgrading the import file formats when I run into issues. Which
Wizards like to throw at me regularly with adding something "new and
exciting!" every damn set;)

The fix isn't perfect, either. I'd LIKE to keep the card data intact and
proper in the event I end up doing something else with it, and now this
card's data is a little hacked up, but only the stuff I'm not using mtgen
users would never know.

I've been trying to think up a better solution, like the split you
mentioned, but I can't think of any way that wouldn't be a ton of work
and/or compromise performance (which isn't as fast as I'd like as it is).
