### ISSUE TITLE
More modularity

### ISSUE THREAD

**Issue by goblin** [copperdogma/mtgen#7]
Hiya,

In https://github.com/copperdogma/mtgen/issues/5 I mentioned secure generation. I've implemented an alpha version at https://github.com/goblin/dierk (live at https://goblin.github.io/dierk/). 

To test it you need to append some stuff to the URL, i.e. make it https://goblin.github.io/dierk/#players=alice,bob;sets=1kld.kld-standard

I've re-implemented the card generation bit from mtgen, in genbooster.js. Navigating just to
https://goblin.github.io/dierk/genbooster.html#seed=00000000000000000000000000000000;sets=1kld.kld-standard will skip the multi-party seed generation and will just generate you 1 Kaladesh booster from the random seed of 16-byte zeroes.

genbooster.js was just a quick and dirty thinned down reimplementation of the stuff in mtgen. I was aiming for fewer dependencies, simplicity and the ability to seed the random number generator (which stuff like `_.sample` doesn't seem to support).

I guess this issue is just informative only, but if you'd like to change up your code so that it can be used as a drop-in replacement for genbooster.js (and be more correct at the same time), I'd really appreciate! It uses a random number generator that's passed to the genbooster's constructor. The interface to the random number generator is just one function, `getrange(x)`, which returns you a random number from the range [0-x).

If you have any comments or questions, let me know :-)

**Comment by copperdogma** [comment]
This is amazing. I'm not even going to pretend I understand encryption well
enough to know what you're doing, but it's impressive.

I'll add incorporating what you modularized or something similar to my
list. It's a long list, though, so it may take awhile;)

**Comment by copperdogma** [comment]
Done! Merged all of your changes, refactored, and pushed them to master.

Note: If you've already implemented anything using my old lib, I made some minor breaking changes: name of the js lib file has changed, the main method you call was renamed (was renderInput(), now called renderBoosterSelectors()), and the return is slightly different. It's now a wrapper around the list of rendered card sets, and that wrapper included the seed used.


Enjoy! And thanks agian.

**Comment by goblin** [comment]
Amazing, awesome, much thanks! :-)

I've just updated my Deck Editor at https://github.com/goblin/dierk according to your renames. I'm not using `renderInput()` but `generateCardSetFromPack()`... not sure if that's right ;-) Seems to work for now, if the API changes I'll fix it.

You mentioned you want to make a deck editor yourself: you might want to take a look at mine ;-) It's meant to be quite advanced and it's missing a lot of documentation and UI hints/fixes (as well as `diff`erencing card lists and scryfall search), but it's getting pretty usable for me already.

**Comment by goblin** [comment]
The main URL is https://goblin.github.io/dierk/de.html , but you can see some cards if you go to e.g. https://goblin.github.io/dierk/de.html#seed=abc;sets=1bro.bro-draft . I'd be interested to know if anyone except me can make sense of it ;-)

**Comment by copperdogma** [comment]
Thanks so much! I'll take a look when I get a chance. I need to get back to
some other stuff after this burst of work on mtgen, though.
