### ISSUE TITLE
Oath of the Gatewatch boosters produce non-full-art Wastes

### ISSUE THREAD

**Issue by SilverNexus** [copperdogma/mtgen#8]
![2017-01-07-212208_1366x768_scrot](https://cloud.githubusercontent.com/assets/3587118/21746793/af7cd8b4-d51f-11e6-9237-90b7fb2173e7.png)
![2017-01-07-212213_1366x768_scrot](https://cloud.githubusercontent.com/assets/3587118/21746794/af83d3ee-d51f-11e6-8559-a2f0cf33565e.png)
If I recall correctly, only the intro pack should have non-full-art Wastes. Everything else does full at Wastes.
It's also worth noting that it does produce full-art Wastes, too. It seems to produce the other ones as well, making me suspect something just needs to be set on the non-full-art ones to make them not show up.

**Comment by copperdogma** [comment]
Right you are! Thanks. Fixed!
